{% set version = "1.0.9" %}

package:
  name: vcflib
  version: {{ version }}

source:
  url: https://github.com/vcflib/vcflib/releases/download/v{{ version }}/vcflib-{{ version }}-src.tar.gz
  sha256: 493204cb8e0515defa1383d56280d00b8efbed55312c6055162f8cb3a4ffb210
  patches:
    - shared_lib.patch
    - pkg-config.patch

build:
  number: 0

requirements:
  build:
    - make
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    # python really only used as a build tool; no ${PREFIX}/bin/python needed.
    - python >=3
    - cmake
    - pkg-config
    - zig
  host:
    - htslib
    - tabixpp
    - pybind11
  run:
    - python >=3
    - zlib   
    - htslib
    - tabixpp

test:
  commands:
    - vcfallelicprimitives -h
    - vcffirstheader < /dev/null
    - vcfsort < /dev/null
    - vcfrandom | grep 'fileformat=VCF'
    - vcfcreatemulti -h

about:
  home: https://github.com/vcflib/vcflib
  license: MIT
  summary: Command-line tools for manipulating VCF files
  maintainers: jpuritz

extra:
  identifiers:
    - biotools:vcflib
    - doi:10.1101/023754
